### ISSUE TITLE
Documentation bug: docs on #:...bind have disappeared

### ISSUE THREAD

**Issue by wilbowma** [racket/redex#101]
I have no idea when this happened, but I don't see the documentation on `#:...bind` anymore. There used to be a great (well, good) section explaining some of more complicated parts of the binding-forms features, like `#:...bind` and how to get the right binding semantics of `let` and `let*`. This section seems to have been replaced by some toy examples in `define-language` that give `let` totally backwards semantics.

**Comment by rfindler** [comment]
would you mind looking back at 6.7 and 6.6 and ... to try to find the ones
you liked to give me a little hand in sorting this out?

**Comment by wilbowma** [comment]
It looks like v6.6 (cf84e599032cad44cbbae42ae6f88598149eb322) had it but v6.7 (70351865aee1fd87dc484f067088cdd837a8fea7).

**Comment by rfindler** [comment]
Oh, I understand what you think went away now. I need a little more help to understand what your complaint is. Specifically: in what sense is this a semantics of let? In what sense is something backwards?

**Comment by rfindler** [comment]
Here's is, I believe, the way `let` is specified in the current docs:

#lang racket
(require redex/reduction-semantics)

```
(define-language L
  (e ::= (let ([x e] ...) e) x natural (+ e e))
  (x ::= variable-not-otherwise-mentioned)
  #:binding-forms
  (let ([x e_x] ...)
    e_body #:refers-to (shadow x ...)))
```

I'm not seeing anything backwards. In particular, this gives the right answer as far as I can tell?

```
> (term
   (substitute
    (let ([x y][y x]) (+ x y))
    z 99)
   #:lang L)
'(let ((x«2» y) (y«3» x)) (+ x«2» y«3»))
```

I do agree that the docs for `#:...bind` are now gone and they need to come back.

I don't agree that the old docs were what we want, however. 

I would be delighted if you were to help out by suggesting some examples (of actually running code, preferably the pick up where the current docs leave off) that illustrate how to use `#:...bind` successfully. I'm not sure that the old docs quite met this bar. And I am sorry that I never got back to finishing that rewrite.

**Comment by wilbowma** [comment]
With regard to `let`, consider this example from the docs.

```racket
(term (substitute (let ([x 1] [y x] [x 3]) x)
                    x
                    z) #:lang lc-bind+let)

'(let ((x«2» 1) (y«3» z) (x«4» 3)) x«2»)
```

The *later* `x` is shadowed by the *earlier* `x`. That seems entirely backwards to me.

**Comment by rfindler** [comment]
That's not an expression (backwards or forward), that's a syntax error.

```
Welcome to Racket v6.9.0.4.
> (let ([x 1] [y x] [x 3]) x)
; readline-input:1:19: let: duplicate identifier
;   at: x
;   in: (let ((x 1) (y x) (x 3)) x)
; [,bt for context]
```

**Comment by wilbowma** [comment]
I agree that the old docs weren't ideal. They were not in the wrong place and should have been located with `define-language`. They needed to explain the syntax and grammar of `#:binding-forms` a little more directly and needed more simple examples, which the current docs do better.

I'll see about contributing to the docs.

**Comment by wilbowma** [comment]
It may not be a Racket expression, but it's a valid `lc-bind+let` expression with bizarre behavior, and needs `#:...bind` to correct it.

**Comment by rfindler** [comment]
Thank you!!!

I'm delighted to help out here. Indeed, a few back and forths with some examples that feel like useful examples of `#:...bind` that build up an intuition is what I need to get going. After that I can take over....

**Comment by mfelleisen** [comment]
@rfindler William is talking about the model, not Racket.

**Comment by wilbowma** [comment]
Here is a simple example that uses `#:...bind`. Beyond how I've used it here, I only know as much about `#:...bind` as I get from error messages when I make a typo.

```racket
#lang racket
(require redex/reduction-semantics)

(define-language λL
  (x ::= variable-not-otherwise-mentioned)
  (e ::= x (λ (x ...) e) (e e ...))
  #:binding-forms
  (λ (x #:...bind (xs x (shadow xs x))) e #:refers-to xs))

(define-metafunction λL
  subst-all : any (any ...) (any ...) -> any
  [(subst-all any () ()) any]
  [(subst-all any (any_x any_xs ...) (any_a any_as ...))
   (subst-all (substitute any any_x any_a) (any_xs ...) (any_as ...))])

(define λL-->
  (reduction-relation
   λL
   (--> ((λ (x ..._0) e_body) e ..._0)
        (subst-all e_body (x ...) (e ...)))))

(define λL-->*
  (compatible-closure λL--> λL e))

(define-metafunction λL
  eval : e -> e
  [(eval e)
   ,(car (apply-reduction-relation* λL-->* (term e) #:cache-all? #t))])

(module+ test
  (require redex-chk)
  (redex-chk
   #:lang λL
   (eval ((λ (x) x) A)) A
   (eval ((λ (x x) x) A B)) B
   (eval ((λ (x x x) x) A B C)) C
   (eval ((λ (x x y) x) A B C)) B
   (eval ((λ (x z y) x) A B C)) A
   (eval ((λ (x z y) z) A B C)) B
   (eval ((λ (x z y) y) A B C)) C))
```

**Comment by rfindler** [comment]
@mfelleisen : I understand @wilbowma's comments.

**Comment by rfindler** [comment]
(@wilbowma apparently mine weren't clear: I'm saying that this isn't an error in the binding specification of that language; it is a missing syntactic check saying that duplicate variables in a `let` expression is not an expression.)

**Comment by wilbowma** [comment]
Ah I see. Okay. Then an example with `let*` as a primitive form would require `#:...bind`.

**Comment by rfindler** [comment]
Yes! 

I'm trying to play around with your lambda expression, as I like how it has fewer moving pieces than `let*` would. But this is a dense little sublanguage, so I find it hard to unpack and explain.

**Comment by wilbowma** [comment]
It's certainly not intuitive why a programmer would ever write `(lambda (x x x) x)`. But remember, most programs aren't written by programmers; they're written by other programs.

**Comment by rfindler** [comment]
I've pushed a change to redex's docs to try to explain `#:...bind`. How does it look?

Also, I think the right change to put `#:...bind`, `#:refers-to` and `#:exports` is to somehow give a definition of `binding-pattern` in the grammar attached to `define-language`. Does that sound right? Would it look something like:

```
binding-pattern ::= pattern | binding-pattern #:refers-to beta | binding-pattern #:exports beta
```

with a note in English that `pattern` is really all of the redex patterns inlined there, so that the keywords can appear anywhere throughout the pattern? (And maybe dropping `binding-declaration`, replacing references to it with `binding-pattern`?)

**Comment by wilbowma** [comment]
Thats look pretty good, and I think the additional headings are useful for skimming the documentation.

Regarding finally documenting `binding-pattern`, YES. Thank you. I keep forgetting to mention that is used but never defined. Related, #88. I think this definition does replace `binding-declaration`, but you or @paulstansifer would know better.

**Comment by wilbowma** [comment]
One additional thought: it would be nice to connect the documentation of `#:...bind` to the error message you get when it's malformed. For example, if you use mistype it as `.... #:...bind (clauses (shadow clauses x)) ....`. you get an error message talking about import and exports:

```racket
 define-language: #...bind must be followed by `(name tail-imports tail-exports)` 
```
The documentation speaks in terms of exports, but I'd like to say something that directly connect to this error message.

I think of it something like this: we give the sequence of clauses processed so far, e.g., `x_0 ... x_{i-1}`, a name, e.g. `clauses`. At each step `i` in the sequence, we import some names (in this case `x_i`), and export some names (in this case the `clauses` processed so far with `x_i` shadowing any equal name).

**Comment by rfindler** [comment]
@paulstansifer I pushed what I think is a reasonable way to describe binding patterns. Does it seem wrong to you?

I'm attaching a screenshot of the rendered grammar. There is also a note below in the text that says that binding pattern annotations can go anywhere nested inside, too.

![screen shot 2017-05-24 at 7 45 24 am](https://cloud.githubusercontent.com/assets/399024/26403775/11198446-4055-11e7-9542-59f748278254.png)


https://github.com/racket/redex/commit/0a0122a01bee555d481817b42200e11ff48e41aa

**Comment by rfindler** [comment]
oh, wait: that's actually `(id beta beta)`, after `#:...bind` isn't it? I've pushed that change.

**Comment by rfindler** [comment]
@wilbowma , yes that's a good idea. I've pushed a change that syncs those two up. Is that what you had in mind?

**Comment by paulstansifer** [comment]
I don't believe that the `binding-pattern #:refers-to beta` line is necessary; `#:refers-to` can occur anywhere in a `binding-pattern`. Otherwise, it looks good.

**Comment by rfindler** [comment]
@paulstansifer if I remove the `binding-pattern #:refers-to beta` line, then `#:refers-to` won't appear anywhere in the grammar, right? That doesn't seem right?

**Comment by wilbowma** [comment]
That's better, but what I had in mind was that the word "imports" in `tail-imports` doesn't appear in any of the descriptions in about `#:...bind`, see https://github.com/racket/redex/blob/69bff2ab4dc4283ba22720807e588be20e564a92/redex-doc/redex/scribblings/ref/languages.scrbl#L326. (Nor "tail" for that matter.) If it's important that these are imports, we should describe them as imports. Otherwise, we should just call it a `beta`.

**Comment by paulstansifer** [comment]
@rfindler The definition of `binding-pattern` should mention `#:refers-to`;
it should be possible for any subterm of it to `#:refers-to` a beta.

**Comment by wilbowma** [comment]
@paulstansifer Isn't that what this grammar specifies?

**Comment by rfindler** [comment]
I would not object to someone fleshing out the tail and the imports/exports distinctions in the docs and implementation error checking, but for now I've just removed it.

**Comment by paulstansifer** [comment]
@wilbowma Yes, I was responding to @rfindler's concern that my proposed
change removed all references to `#:refers-to`. "Should" was supposed to
sound like "probably does".

On Wed, May 24, 2017 at 1:04 PM, William J. Bowman <notifications@github.com

**Comment by rfindler** [comment]
@paulstansifer I'm not following. Would you say that the blue box grammar should change in the current docs?

**Comment by rfindler** [comment]
I think we've reached a fixed point here. I'll close this now, but please feel free to reopen if there are further improvements to be made.
