### ISSUE TITLE
n-ary relations no longer work

### ISSUE THREAD

**Issue by dvanhorn** [racket/redex#107]
This used to work:
```
#lang racket
(require redex)
(define-language REDEX)

(define-relation REDEX
  unique ⊆ any × ...
  [(unique any_!_1 ...)])
```
but now I get a syntax error:
```
define-relation: found an ellipsis outside of a sequence at: ... in: ...
```
This worked at least in the version (6.3) of Redex around March, 2016.

Was this an intentional backwards compatible change or is it a bug?  (There is an easy workaround, which is to use a list.)

**Comment by wilbowma** [comment]
Looks like this was introduced between (6.7,6.9]. I can try to bisect more later.

**Comment by bennn** [comment]
Probably https://github.com/racket/redex/commit/fe3c4ac5fc4b4a7dddc60b500907dc908396d04a
#90

**Comment by wilbowma** [comment]
Irony confirmed: "[baf69d62977cabfbb7cc010b13741ed75943a55f] adjust the way judgment forms work so that define-relation generally works more"

**Comment by rfindler** [comment]
Apparently there is not a total ordering on "works" so I shouldn't have used words that imply that ;)

That said, the commit did cause strictly more of the test cases to pass! (Too bad one along the lines of this PR wasn't in there.)
