### ISSUE TITLE
DOC: static distance function `sd` is incorrect

### ISSUE THREAD

**Issue by haroldcarr** [racket/redex#111]
`sd` in `.../redex-doc/redex/scribblings/long-tut/mon-aft.scrbl`

Robby showed a fix in email:

    (define-extended-language SD Lambda2
      (e ::= .... (K n n))
      (n ::= natural))

    (define sd1 (term (K 1 1)))
      [(sd/a e_1 (e_rib ...))
       ; a free variable is left alone
       e_1])

Matthias showed a fix (but missing closing bracket and paren):

    #lang racket
    
    (require redex)
    
    (define-language Lambda
      (e ::= x
         (lambda (x ...) e)
         (e e ...))
      (x ::= variable-not-otherwise-mentioned))
    
    ; (sd e) computes the static distance version of e
    (define-extended-language SD Lambda
      (e ::= .... (K n n))
      (n ::= natural))
     
    (define sd1 (term (K 1 2)))
    (define sd2 (term 1))
     
    (define SD? (redex-match? SD e))
     
    (module+ test
      (test-equal (SD? sd1) #true))
    
    
    (define-metafunction SD
      sd : e -> e
      [(sd e_1) (sd/a e_1 ())])
     
    (module+ test
      (test-equal (term (sd/a x ())) (term x))
      (test-equal (term (sd/a x ((y) (z) (x)))) (term (K 2 0)))
      (test-equal (term (sd/a ((lambda (x) x) (lambda (y) y)) ()))
                  (term ((lambda () (K 0 0)) (lambda () (K 0 0)))))
      (test-equal (term (sd/a (lambda (x) (x (lambda (y) y))) ()))
                  (term (lambda () ((K 0 0) (lambda () (K 0 0))))))
      (test-equal (term (sd/a (lambda (z x) (x (lambda (y) z))) ()))
                  (term (lambda () ((K 0 1) (lambda () (K 1 0)))))))
     
    (define-metafunction SD
      sd/a : e ((x ...) ...) -> e
      [(sd/a x ((x_1 ...) ... (x_0 ... x x_2 ...) (x_3 ...) ...))
       ; bound variable 
       (K n_rib n_pos)
       (where n_rib ,(length (term ((x_1 ...) ...))))
       (where n_pos ,(length (term (x_0 ...))))
       #;(where #false (in x (x_1 ... ...)))]
      [(sd/a (lambda (x ...) e_1) (e_rest ...))
       (lambda () (sd/a e_1 ((x ...) e_rest ...)))]
      [(sd/a (e_fun e_arg ...) (e_rib ...))
       ((sd/a e_fun (e_rib ...)) (sd/a e_arg (e_rib ...)) ...)]
      [(sd/a e_1 any) ;; MF: fix 1

**Comment by mfelleisen** [comment]
What is truly worrisome about this comment is that I ran my proposal in drracket and copied it into the email. How Harold could have gotten code with missing brackets and parens is beyond me.
