### ISSUE TITLE
substitute fails in non-variable base case

### ISSUE THREAD

**Issue by dvanhorn** [racket/redex#113]
This is my first time using binding forms, so maybe I'm doing something dumb, but I can't seem to make `substitute` work -- it crashes when getting to a base case that is not a variable occurrence complaining about not having a case that matches:

```
#lang racket
(require redex)
(define-language Λ
  (M ::= X 0 (M M) (λ X M))
  (X ::= variable-not-otherwise-mentioned)
  #:binding-forms
  (λ X M #:refers-to X))

(define-relation Λ
  β ⊆ M × M
  [(β ((λ X M_1) M_2) M_3)
   (where M_3 (substitute M_1 X M_2 #:lang Λ))])

(term (β ((λ x 0) 0) 0))
```
substitute: no clauses matched for (substitute 0 x«0» 0 #:lang Λ)

(This is 6.9.)

**Comment by mfelleisen** [comment]
Try default-language instead: 

#lang racket
(require redex)
(define-language Λ
  (M ::= X 0 (M M) (λ X M))
  (X ::= variable-not-otherwise-mentioned)
  #:binding-forms
  (λ X M #:refers-to X))

(default-language Λ)

(define-relation Λ
  β ⊆ M × M
  [(β ((λ X M_1) M_2) M_3)
   (where M_3 (substitute M_1 X M_2))])


(term (β ((λ x 0) 0) 0))

**Comment by dvanhorn** [comment]
Uh... OK.  This seems weird.  The default language is being set to Λ if I omit it, but if I specify it explicitly, it behaves differently.  (I also just noticed that the occurrence of Λ in #:lang doesn't have an arrow from its definition; I can unquote that position, but it still fails in the same way.)  

Seems like I *must* use the default language; anything else breaks.

**Comment by mfelleisen** [comment]
That’s what I discovered as in preparation of the Racket school. 

[Apologies I didn’t report this to the repo.]

**Comment by rfindler** [comment]
I'm not completely sure about the rest of this thread, but I think that if you put a `#:lang` down inside a term, it just means that your (object) language is using keywords (which is probably not what's intended here). 

I would have expected that this program does not raise any errors and, indeed, when I run it, it does not raise any errors and returns `#t` (which seems to contradict @mfelleisen and @dvanhorn 's assertions above, so I don't know what to make of that). Am I missing something?

```
#lang racket
(require redex)
(define-language Λ
  (M ::= X 0 (M M) (λ X M))
  (X ::= variable-not-otherwise-mentioned)
  #:binding-forms
  (λ X M #:refers-to X))

(define-relation Λ
  β ⊆ M × M
  [(β ((λ X M_1) M_2) M_3)
   (where M_3 (substitute M_1 X M_2))])

(term (β ((λ x 0) 0) 0))
```

**Comment by mfelleisen** [comment]
I got the same error as  @dvanhorn so it was repeatable for some git head version last week. 

Did you possibly fix something? I did mention a different misinterpretation about #:lang to you.

**Comment by dvanhorn** [comment]
Ah, I see what happened, I read the examples as (term (substitute ... #:lang ...)) when it's really just the usual (term ... #:lang ...).  It was something silly on my part after all.

**Comment by dvanhorn** [comment]
The error does not occur in the code both @mfelleisen and @rfindler wrote; just in the code I started with because I was putting #:lang in a position that doesn't make sense.
