### ISSUE TITLE
substitute compatible with generate-term

### ISSUE THREAD

**Issue by dvanhorn** [racket/redex#114]
This is a feature request for something which may not be possible, but it would be really nice if the `substitute` metafunction were written in a way to be compatible with term generation.  Here is a small program that crashes, which I would like to work:

```
#lang racket
(require redex/reduction-semantics)
(define-language L)
((generate-term L #:satisfying (substitute any variable 0) = 0) 0)  
```

**Comment by rfindler** [comment]
I believe this is a request for alpha-prolog. I agree that would be nice. :)

**Comment by dvanhorn** [comment]
For a specific language I (believe I) can write subst without ellipses, unquoting, etc., which is what generate-term complains about here.  Maybe it's not possible in general.

 BTW, I came across this by trying to randomly test type preservation by generating from a judgment on typed, reducible terms.

**Comment by dvanhorn** [comment]
I take that back -- you'll need a where clause for computing unused variables (if written in the usual way).

**Comment by rfindler** [comment]
FWIW, I think this is relatively well-trod ground (altho I'm sure there is something new to discover in there!), and it would be great to add nominal logic to the solver inside Redex, or change it to use an external solver that supported nominal logic already.

**Comment by dvanhorn** [comment]
I'm closing this since I thought I was asking for something simpler.

**Comment by rfindler** [comment]
I didn't add, but one other thought that I had here: my guess is that if you did the "straightforward" translation of creating a substitution judgment form and then used the existing solver, I guess you are right that it would work, but that it would not be a very effective generator. My guess is that extending the language of the solver itself is probably the right.

But I haven't tried out basic things to see if that's right or not.
