### ISSUE TITLE
Long Tutorial (why doesn't unique-vars work?)

### ISSUE THREAD

**Issue by migeed-z** [racket/redex#115]
In section 2.2.2 we create `unique-vars` metafunction, which determines if a sequence of variables has no repetitions. But the notes then mention:

>Sadly, `unique-vars` doesn’t work for our language definition. They create circular definitions.

But no further explanation is given. This doesn't make sense. Can someone clarify the tutorial?

**Comment by rfindler** [comment]
I think what it is saying is that, if `unique-vars` were to be useful, it would have to be used in the language definition itself, but it can't be used in the language definition since it needs the language definition to even be defined.

@mfelleisen is that it?

**Comment by mfelleisen** [comment]
Correct. 

[But we may wish to revisit the pedagogical decision to develop the whole metafunction here, only to say at the end “sorry, this was a detour.]
