### ISSUE TITLE
Internal error when using binding-forms

### ISSUE THREAD

**Issue by dfeltey** [racket/redex#118]
This program:

```
#lang racket

(require redex)

(define-language L
  (p ::= ((def (x x) x) ...))
  (x ::= variable-not-otherwise-mentioned)
  #:binding-forms
  ((def (x_1 x_2) x_3 #:refers-to (shadow x_1 ... x_2)) ...))

(default-language L)

(term (substitute ((def (f x) f)) x x))
```

Produces the error message:
```
racket/dev/clones/redex/redex-lib/redex/private/binding-forms.rkt:418:2: second: contract violation
  expected: list?
  given: 'f«0»
```

**Comment by wilbowma** [comment]
I'm guessing your point is that this error message needs to be improved. Note that program is invalid, since x_1 is not a list when it is followed by an ellipsis, but of course most users wouldn't know that from the error message produced.

--

**Comment by dfeltey** [comment]
@wilbowma Yes, this should be caught earlier as an error rather than signalling a contract application from a bad application of `second`

**Comment by rfindler** [comment]
Looks like the `shadow` ellipsis checking isn't happening even in this program (which, I believe, should also be a syntax error):

```
#lang racket

(require redex/reduction-semantics)

(define-language M
  (p ::= (def x x))
  (x ::= variable-not-otherwise-mentioned)
  #:binding-forms
  (def x_1 x_2 #:refers-to (shadow x_1 ...)))

(default-language M)

(term (substitute (def f f) x x))
```

**Comment by rfindler** [comment]
I see what's going on. The code has its own hand-rolled check for ellipsis depth but it doesn't (can't) work because it doesn't have the right information.

**Comment by rfindler** [comment]
I've pushed a fix for this:

https://github.com/racket/redex/commit/e8739f87a41c21295a0bcab1d8ab6c5a45c43092
