### ISSUE TITLE
Can't use in-hole with an extended context

### ISSUE THREAD

**Issue by wkunkel** [racket/redex#128]
Using an `in-hole` pattern in an extended language fails when the context is an extension of a nonterminal in the base language. For example, given the file
```racket
#lang racket
(require redex/reduction-semantics)

(define-language foo
  [v ::= unit]
  [E ::= hole])

(define-extended-language bar foo
  [E := ....])
```
evaluating `(redex-match? foo (in-hole E unit) (term unit))` returns `#t` as expected, but `(redex-match? bar (in-hole E unit) (term unit))` errors with

```
in-hole's first argument is expected to match exactly one hole, but it may match a hole many different ways
  in: (in-hole E unit)
Context:
 /usr/share/racket/pkgs/redex-lib/redex/private/rewrite-side-conditions.rkt:37:2 rewrite-side-conditions/check-errs11
 /usr/share/racket/pkgs/redex-lib/redex/private/reduction-semantics.rkt:1120:0 test-match/both
```

If `bar` is instead defined as `(define-extended-language bar foo)`, the problem disappears, even though I would expect these definitions to be equivalent.

**Comment by philnguyen** [comment]
In `bar`, you're having `:=` instead of `::=`

**Comment by wkunkel** [comment]
Haha, you're totally right, changing that fixes it. That's a strange way for that error to manifest; in general it's not clear to me why
```racket
#lang racket
(require redex/reduction-semantics)

(define-language foo
  [v ::= unit]
  [E ::= hole])

(define-extended-language bar foo
  [E ::= baz ....])
```
should cause an error on `(redex-match? bar (in-hole E unit) (term unit))` instead of just matching with E bound to `hole`.

**Comment by wkunkel** [comment]
Actually, thinking about it more, it makes sense: `in-hole E baz` would be ambiguous.
