### ISSUE TITLE
render-derviation

### ISSUE THREAD

**Issue by jeapostrophe** [racket/redex#131]
It would be cool to be able to render a derivation tree that uses a judgment form so we can demonstrate how the proof rules work.

**Comment by jeapostrophe** [comment]
@reamslin You can try to do this. Maybe @rfindler has advice? It looks like `derivation/ps` does something similar, but doesn't seem to produce a pict, or maybe it does in the implementation.

**Comment by rfindler** [comment]
Why not use `show-derivations` ?

**Comment by jeapostrophe** [comment]
We want a pict for a paper. So perhaps we can just look in the implementation of that?

**Comment by rfindler** [comment]
It isn't set up to work with picts, but yes, there is a common abstraction that it and a pict-based one could use. That would be great to have!
