### ISSUE TITLE
Documentation for terms doesn’t mention many literal values

### ISSUE THREAD

**Issue by leafac** [racket/redex#139]
[The grammar for terms](https://docs.racket-lang.org/redex/The_Redex_Reference.html#%28part._.Terms%29) includes booleans and strings, but not numbers, hashes, prefab structs and so forth. The documentation does mention that `term` is similar to `quasiquote`, so it’s implied that all these kinds of data work, and they in fact do:

```racket
#lang racket
(require redex)

(term 42) ;; => 42
(term #hash((answer . 42))) ;; => '#hash((answer . 42))
(term #s(pirate 42)) ;; => '#s(pirate 42)
```

I propose we change the grammar to include all literal values.

**Comment by rfindler** [comment]
I'm somewhat skeptical of this because they don't really work. For example, this program:

```
#lang racket
(require redex)
(define-language L
  (e ::= #s(s 1 e ...) hi))
(redex-match L e (term #s(s 1 hi)))
```

produces `#f` but I guess that should produce `#t`.

I would prefer to limit redex's pattern matching language to make this a syntax error, but that is also a problematic response as people probably find this kind of thing useful in general.

**Comment by leafac** [comment]
I propose a compromise: The documentation acknowledges that literal values can be terms, but says that they’re **opaque**: the `e` in `#s(s 1 e ...)` is as meaningful as it is in `"abcde"`.

**Comment by rfindler** [comment]
That sounds reasonable to me. How do you feel about working out some nice test cases that can go along with the changes to the documentation to alert me when I break the promises you have in mind to include?

**Comment by leafac** [comment]
There you have it. It wasn’t even that much work, because most tests were already there. Terms involving integers, for example, are used all over the place, but the documentation didn’t acknowledged them.
