### ISSUE TITLE
The redex-check form does not correctly respect _!_

### ISSUE THREAD

**Issue by cgswords** [racket/redex#15]
The redex-check form does not correctly respect `_!_` for variables in sufficiently large examples. A gist containing code that produces this error may be found here: https://gist.github.com/cgswords/8f6ddb6174dc7db64603 (Warning: that is a full redex mode, not a boiled-down counter-example.)

Upon further investigation, the following was discovered:

    < ianjneu> cswords: redex-lib/redex/private/enum.rkt:176 _!_ is unimplemented. It just doesn't warn you.
    < ianjneu> it should raise an error. "unimplemented" raises an error. It doesn't.

For a temporary solution, we can define:

    (define-judgment-form ccon #:mode (Good-e I) [--- (Good-e e)])

The generator can then use 

    #:satisfying (Good-e e)

Unfortunately, this disable retries.

**Comment by ianj** [comment]
Where sufficiently large includes the lambda calculus
```racket
#lang racket
(require redex)
(define-language L
  [e x (e e ...) (lambda (x_!_ ...) e)]
  [x variable-not-otherwise-mentioned])
(redex-check L e_chk (redex-match? L e (term e_chk)))
```

**Comment by rfindler** [comment]
@ianj 's example was fixed in late July, but hasn't made it to a release yet.

**Comment by cgswords** [comment]
While Ian's example works in the nightly build of racket, the larger calculus I linked above still produces lambdas with multiple variables of the same name.

**Comment by rfindler** [comment]
I adjusted the code in the gist by deleting all of the uses of
`redex-check` and then putting this at the bottom of the file:

```
(random-seed 0)
(define is-P? (redex-match? ccon P))
(redex-check ccon P is-P? #:attempts 1500)
```

and I am not seeing any failures. Could you please make some adjustments to
what I've done to clarify the bad behavior you're seeing?

Thank you,
Robby

**Comment by cgswords** [comment]
The following will reproduce the error consistently:

    random-seed 0)
    (define is-e? (redex-match? ccon e))
    (redex-check ccon e is-e? #:source step #:attempts 3000)

The output is:

    redex-check: (predc (if ((lambda (W E W Y) JwX) (thunk (case k D nqF X B)) (thunk (+ t O)) 5 (inr unit)) u L)) does not match e

**Comment by rfindler** [comment]
That's because this clause in `step`:

```
(in-hole E ((lambda (x ..._1) e) tv ..._1))
```

generates things that are not `e`s.

I can see how this is confusing, and that there is really not anything you can reasonably do to compensate, so I've pushed a change to Redex so that it just discards such test cases instead of signaling errors.

https://github.com/racket/redex/commit/ba99493f3f185b031ac2a50f78df9aa23238d18f

**Comment by cgswords** [comment]
Ah! Thanks so much for all the help with this.
