### ISSUE TITLE
judgment-form side-condition documentation incorrect

### ISSUE THREAD

**Issue by pnwamk** [racket/redex#152]
The documentation for `side-condition` clauses for `define-judgment-form` is incorrect/misleading. It states:

```
...a premise of the form (side-condition term) is equivalent to the 
premise (where #t term), except it does not typeset with the 
“#t = ”, as that would.
```

when in reality it does not check for `#t`, but for _any_ non-`#f` value:

```racket
#lang racket/base

(require redex)

(define-language L
  [n ::= number])

(define-judgment-form L
  #:mode (j I)
  #:contract (j any)
  [(side-condition any-non-false-value)
   -----------------
   (j n)])

(judgment-holds (j 42)) ;; => #t
```

IMHO, what the documentation suggests is actually a little more sane than the current behavior, since explicitly checking for `#t` seems to me like it would greatly reduce errors that are easily introduced by forgetting that this is the only `side-condition` form in redex which _does not_ unquote the rhs implicitly (and thus you can easily write a non-`#f` value on the rhs of a `side-condition` without realizing it's just a quoted sexp).

Of course if there's worry that some programs _depend_ on the current (IMHO strange) behavior maybe the docs should just be updated to warn the user appropriately.

**Comment by rfindler** [comment]
I don't think that we can change this; too many things in Racketdom are truthy. I do see what you mean, tho.

**Comment by maxvonhippel** [comment]
@rfindler what does `truthy` mean?  (I don't intend to suggest this issue should be re-opened, I'm just asking for my own educational benefit.  Thank you!)

**Comment by pnwamk** [comment]
Not Robby but I'm here: values which are "treated as true", which in Racket is all those which are not `#f` (i.e., those which will cause execution to enter then "then"-branch of an `if` if used in the test-position, which any value but `#f` does).

**Comment by rfindler** [comment]
@maxvonhippel also, do the docs in the commit above help clarify?

**Comment by maxvonhippel** [comment]
Yep, that makes sense, thank you!  (I assumed this was what it meant, but wanted to make sure.)
