### ISSUE TITLE
‘apply-reduction-relation*’ doesn’t work with ‘IO-judgment-form?’

### ISSUE THREAD

**Issue by leafac** [racket/redex#155]
Consider the following program:

```racket
#lang racket
(require redex)

(define-language L)

(define-judgment-form L
  #:mode (f I O)
  [(f 1 2)]
  [(f 2 3)])

(IO-judgment-form? f) ;; => #t

(apply-reduction-relation f 1) ;; => '(2)

(apply-reduction-relation* f 1)
;; reduction-relation-lang: contract violation
;; expected: reduction-relation?
;; given: #<judgment-form:f>
```

I believe the last expression shouldn’t result in an error, because [the documentation](https://docs.racket-lang.org/redex/The_Redex_Reference.html?q=apply-reduction-relation#%28def._%28%28lib._redex%2Freduction-semantics..rkt%29._apply-reduction-relation%2A%29%29) says `apply-reduction-relation*` can work with an `IO-judgment-form?`.

**Comment by leafac** [comment]
Thank you, @rfindler.

I’m confused: the message on the commit says “fix `apply-reduction-relation*` for judgment forms **that have no contract**”, but having a contract or not doesn’t influence the outcome. For example, the following program also fails (it’s a variation on the program from my original description in which `#:contract` is specified):

```racket
#lang racket
(require redex)

(define-language L)

(define-judgment-form L
  #:mode (f I O)
  #:contract (f _ _)
  [(f 1 2)]
  [(f 2 3)])

(IO-judgment-form? f) ;; => #t

(apply-reduction-relation f 1) ;; => '(2)

(apply-reduction-relation* f 1)
;; reduction-relation-lang: contract violation
;; expected: reduction-relation?
;; given: #<judgment-form:f>
```

**Comment by rfindler** [comment]
https://github.com/racket/redex/issues/130

**Comment by leafac** [comment]
The problem occurs with `stepper` as well:

```racket
#lang racket
(require redex)

(define-language L)

(define-judgment-form L
  #:mode (f I O)
  [(f 1 2)]
  [(f 2 3)])

(IO-judgment-form? f) ;; => #t

(stepper f 1)
```
