### ISSUE TITLE
Feature request: "Reduce till finish" for graphical tool from `traces`

### ISSUE THREAD

**Issue by philnguyen** [racket/redex#161]
It would be nice to have an option to expand all of the graph at once (if the user believes it's finite), instead of waiting for and pressing the `Reduce` button once in a while.

**Comment by rfindler** [comment]
How about using

 https://docs.racket-lang.org/redex/The_Redex_Reference.html?q=traces#%28def._%28%28lib._redex%2Fgui..rkt%29._reduction-steps-cutoff%29%29

?

**Comment by philnguyen** [comment]
Oh that's. Great. Thanks!
