### ISSUE TITLE
Language nonterminals and (side-conditions (in-hole ...) ...)

### ISSUE THREAD

**Issue by wilbowma** [racket/redex#18]
I'm getting an unexpected error when using side-conditions over in-hole patterns in language nonterminal definitions. The pattern variables don't seem to get bound in the guard expression unless I add an `_` to each pattern name.

E.g. Here is a small example that I think should work:

```racket
#lang racket/base

(require
  redex/reduction-semantics)

(define-language testL
  (e ::= natural x (e e))
  (x ::= variable-not-otherwise-mentioned)
  (Θ ::= hole (Θ e)))

(define-metafunction testL
  arity : x -> natural
  [(arity add1) 1]
  [(arity +) 2])

(define-metafunction testL
  Θ-length : Θ -> natural
  [(Θ-length hole) 0]
  [(Θ-length (Θ e)) ,(add1 (term (Θ-length Θ)))])

(define-extended-language test-redL testL
  (Θv ::= hole (Θv v))
  (v ::= natural
         (side-condition
           (in-hole Θv x)
           (not (equal? (term (Θ-length Θv))
                        (term (arity x)))))))

(module+ test
  (require rackunit)
  (check-true (redex-match? test-redL Θv (term (hole 1))))
  (check-equal?
    (term (Θ-length (hole 1)))
    1)
  (check-true (redex-match? test-redL v (term (+ 1))))
  (check-false (redex-match? test-redL v (term ((+ 1) 1)))))
```

However, this doesn't work unless I change the side-condition pattern to the following (or similar).

```racket
(side-condition
  (in-hole Θv_0 x_0)
  (not (equal? (term (Θ-length Θv_0))
               (term (arity x_0)))))
```

If this is intended, it seems to be poorly documented.

**Comment by rfindler** [comment]
This is intended. I have tried to improve the documentation with this
commit:


https://github.com/racket/redex/commit/773d98059b0626d72d9f564a95de2ab910030a55

What do you think?

**Comment by wilbowma** [comment]
That is more clear, thanks!

**Comment by rfindler** [comment]
Thanks for the feedback!
