### ISSUE TITLE
Bad Macro Error Messages

### ISSUE THREAD

**Issue by maxsnew** [racket/redex#2]
The following all give generic `$macro: bad syntax in $expression` errors:
```racket
(define-language)
(redex-match)
(redex-match lang)
(define-judgment-form)
(reduction-relation)
```

Here's one that's even worse
```racket
> (define-metafunction)
?: bad syntax in: ()
```
What can we do to improve this? Are there racket guidelines for good macro error messages?

**Comment by rfindler** [comment]
The last one is a bug. The former ones seem not too too terrible; I guess it would be nice if they said "expected" something.

**Comment by maxsnew** [comment]
I don't see any difference between those error messages and if 
```
> (/ )
```
just said "runtime error" with no extra information about how it should be used.

**Comment by rfindler** [comment]
I pushed a fix for the obviously buggy one  https://github.com/racket/redex/commit/fcf9516a1722426fb98965441eac13ef92f84e0f

I agree the error messages could be better. I won't do it today.

**Comment by maxsnew** [comment]
Thanks, Robby!

For posterity any further discussion should go here: http://bugs.racket-lang.org/query/?cmd=view&pr=14928
