### ISSUE TITLE
redex-doc undelcared dependency on scribble or scribble-docs

### ISSUE THREAD

**Issue by wilbowma** [racket/redex#20]
I just updated redex-lib and installed redex-doc on a minimal install, but got some errors during installation of redex-doc about scribble/examples not existing. After installing scribble and scribble docs, these errors disappeared.

A quick look suggests this might have been introduced by 15fb87f1e02cef9641cad3bb71807c3d1de14203 and be the result of an undeclared dependency.

**Comment by rfindler** [comment]
Thanks for pointing out the problem.
