### ISSUE TITLE
expose `test-match`

### ISSUE THREAD

**Issue by wilbowma** [racket/redex#202]
I was just writing a tutorial, and noticed `test-match` didn't exist. So I went to add it. Except it does exist! it's just not exposed.

I'm planning to document and expose it, unless there are good reasons not to.

**Comment by rfindler** [comment]
Do you mean `redex-match`?

**Comment by wilbowma** [comment]
Oh I see, it got renamed-out. Well then maybe I'll add it after all.

The problem I'm having is that right now, when I want to right pattern-matching tests, I have to write:
```racket
(test-predicate (redex-match? L any_1) (term e)
```

Seems like there ought to be a `test-` version of `redex-match?`.

**Comment by rfindler** [comment]
Yes, a test version of redex-match sounds nice!

**Comment by wilbowma** [comment]
closed by c1e941b0c3d577ec3e10083bcd3229d96e2b1224
