### ISSUE TITLE
`render-language` can yield a pict error

### ISSUE THREAD

**Issue by camoy** [racket/redex#217]
If you give `render-language` a non-terminal set that contains a non-terminal that doesn't exist, it'll give an error. However, if you give it a non-terminal that does exist (just defined at a lower language level), it'll give a pict error.

```rkt
(require redex)

(define-language L1
  [n ::= number])
(define-extended-language L2 L1)
(render-language L2 #:nts '(n))
```

Yields:
```
cc-superimpose: expected at least one argument, got none
  context...:
   /usr/local/share/racket/pkgs/pict-lib/pict/private/pict.rkt:931:11
   /usr/local/share/racket/pkgs/redex-pict-lib/redex/private/pict.rkt:652:0: make-grammar-pict
```

**Comment by rfindler** [comment]
This one should probably be an error because the `n` non-terminal isn't really one eligible for rendering in the way things are currently working inside redex. You have to use `L1` to be able to render `n`. After `d6ffbc5` it returns an empty pict instead of being an error, at least. 

What's your opinion @camoy ?

**Comment by camoy** [comment]
What about if you set `extend-language-show-union` to `#t`. I think it makes sense to use `#:nts` on the extended language in that case, meaning the empty pict behavior would be more sensible. Right?

**Comment by rfindler** [comment]
Are you thinking just about one layer, @camoy ? Or about the case where the language extends another language and there are actually some non-terminals that get rendered?

**Comment by camoy** [comment]
The second case, I think I may have misinterpreted the error case you proposed.

If I enable `extend-language-show-union`, I would expect to be able to use `#:nts` to control whether a non-terminal is rendered at language `n` even if the non-terminal was only defined at say language `n-5`. However, if a non-terminal isn't eligible for rendering as in my original code example, I think you're right that an error would be preferable.
