### ISSUE TITLE
`judgment-holds` of a modeless judgment fails oddly if that judgment uses a moded judgment

### ISSUE THREAD

**Issue by florence** [racket/redex#222]
Given the program
```
#lang racket
(require redex/reduction-semantics)

(define-language L)
(define-judgment-form L
  #:contract (nat? any)
  [(is-Z? any)
   ---------
   (nat? any)]
  [(nat? any)
   ---------
   (nat? (S any))])
(define-judgment-form L
  #:contract (is-Z? any)
  #:mode (is-Z? I)
  [---------------
   (is-Z? Z)])

(judgment-holds
 nat?
 (derivation
  '(nat? Z)
  #f
  (list (derivation '(is-Z? Z) #f empty))))
```

I get that the judgment does not hold.

However if I remove the mode spec on `is-Z?`, I the judgment does hold!

I would expect either the judgment to hold in both cases, or to get an error from redex in the first case that a modeless judgment doesn't work when used with a moded judgment.

**Comment by rfindler** [comment]
Looks like a bug to me. It is supposed to be okay that a modeless judgment uses moded ones (but not vice-versa).

**Comment by rfindler** [comment]
Okay, I changed my mind! Not a bug, at least according to way things currently work. The `derivation` that is checked is supposed to include only the modeless judgment forms. So this one:

```
(judgment-holds
 nat?
 (derivation
  '(nat? Z)
  #f
  (list)))
```

returns `#t`

**Comment by rfindler** [comment]
This appears to be the same as issue #219 .
