### ISSUE TITLE
make redex require options more visible to newcomers

### ISSUE THREAD

**Issue by onelharrison** [racket/redex#229]
As a new user to both Racket and the redex package, the options for requiring the redex package are not immediately obvious in this repo or the redex tutorials found in the documentation.

After failing to `(require redex)` due to the absence of a GUI and doing a bit of searching, I found the following in the [Redex Reference](https://docs.racket-lang.org/redex/The_Redex_Reference.html):

> The redex library provides all of the names documented here.
> 
> Alternatively, use the redex/reduction-semantics and redex/pict libraries, which provide only non-GUI functionality (i.e., everything except redex/gui), making them suitable for programs that should not depend on racket/gui/base.

I believe this is important information that should be placed in a more visible location where newcomers are more likely to see it.  I reckon the tutorials are a good place (and possibly in the project README too) to put this information.

**Comment by rfindler** [comment]
Did you find this:  https://docs.racket-lang.org/redex/tutorial.html ?

**Comment by onelharrison** [comment]
@rfindler Yes, that's the tutorial I was following that made no mention of the other ways of requiring redex that do not necessitate having a GUI. I also looked at the [Long Tutorial](https://docs.racket-lang.org/redex/redex2015.html).

**Comment by rfindler** [comment]
Does this mean you weren't able to use DrRacket either?

**Comment by onelharrison** [comment]
@rfindler I haven't been using DrRacket because I'm in a headless environment.
