### ISSUE TITLE
Keywords in grammar confuse substitution

### ISSUE THREAD

**Issue by takikawa** [racket/redex#23]
Example:

````
#lang racket/base

(require redex)

(define-language lang
  [e (Λ (x #:kw x) e)
     x
     number]
  [x variable-not-otherwise-mentioned]
  #:binding-forms
  (Λ (x_1 #:kw x_2) e #:refers-to x_1))

(parameterize ([default-language lang])
  (term (substitute (Λ (x_1 #:kw x_2) 0) x_1 1)))
````

The error message that results:

````
symbol=?: contract violation
  expected: symbol?
  given: '#:kw
  argument position: 2nd
  other arguments...:
   'x_1
  context...:
   /home/asumu/plt/racket-git/racket/collects/racket/bool.rkt:19:0: symbol=?
   /home/asumu/plt/racket-git/extra-pkgs/redex/redex-lib/redex/private/binding-forms.rkt:659:10: loop
   /home/asumu/plt/racket-git/extra-pkgs/redex/redex-lib/redex/private/binding-forms.rkt:620:4: loop
   /home/asumu/plt/racket-git/extra-pkgs/redex/redex-lib/redex/private/binding-forms.rkt:620:4: loop
   /home/asumu/plt/racket-git/extra-pkgs/redex/redex-lib/redex/private/binding-forms.rkt:620:4: loop
   /home/asumu/plt/racket-git/extra-pkgs/redex/redex-lib/redex/private/binding-forms.rkt:620:4: loop
   /home/asumu/plt/racket-git/extra-pkgs/redex/redex-lib/redex/private/binding-forms.rkt:620:4: loop
   /home/asumu/plt/racket-git/extra-pkgs/redex/redex-lib/redex/private/binding-forms.rkt:616:0: rec-freshen-spec
   /home/asumu/plt/racket-git/extra-pkgs/redex/redex-lib/redex/private/binding-forms.rkt:146:0: safe-subst
   /home/asumu/plt/racket-git/extra-pkgs/redex/redex-lib/redex/private/reduction-semantics.rkt:1424:42
   /home/asumu/plt/racket-git/racket/collects/racket/private/map.rkt:21:13: map
   /home/asumu/plt/racket-git/extra-pkgs/redex/redex-lib/redex/private/reduction-semantics.rkt:1724:24: loop
   /home/asumu/docs/dissertation/model/ex.rkt: [running body]
````

I'm not entirely sure if keyword literals in Redex patterns are actually considered valid, but they are accepted by `define-language`. So I'm not sure if this is a bug in substitution due to not handling keywords or a bug in `define-language` due to not ruling keywords out.

**Comment by rfindler** [comment]
@paulstansifer what do you think? IMO, this is a design flaw, since I failed to account for hte fact that `#:binding-forms` (and other keywords) could be part of the language proper. So certain things probably won't be expressible, but at least we can avoid this kind of error.

**Comment by paulstansifer** [comment]
I feel like keyword arguments ought to work. I don't see how `#:binding-forms` causes problems, but I do see that languages with `#:refers-to` would be problematic. We should probably explicitly disallow `#:refers-to` (and maybe `#:exports`, though I think it's safe), and let all other keywords work.

**Comment by rfindler** [comment]
Is there a way we can make this work a different way? How about we make it
be a syntax error to use #:refers-to a literal in a language ONLY when the
language contains #:binding-forms? Would that work?

Robby
