### ISSUE TITLE
test-->>∃ uses equal? by default

### ISSUE THREAD

**Issue by yiyunliu** [racket/redex#232]
Here's the line of code that I believe is problematic: [https://github.com/racket/redex/blob/ebd97bab8a11d3bd6ee525554abb2e3c23f501e9/redex-lib/redex/private/reduction-semantics.rkt#L3051](https://github.com/racket/redex/blob/ebd97bab8a11d3bd6ee525554abb2e3c23f501e9/redex-lib/redex/private/reduction-semantics.rkt#L3051)

When `goal` is not a procedure, it has to be a term and therefore alpha-equivalence should be preferred.

**Comment by rfindler** [comment]
Indeed! Thanks.
