### ISSUE TITLE
`traces` doesn't draw arrows after "fix layout"

### ISSUE THREAD

**Issue by wilbowma** [racket/redex#242]
Racket Verison:
```
> racket
Welcome to Racket v8.2.0.2 [cs].
```

OS: macOS 10.14.6

I run the following command:
```
(traces anf->+ #:reduce (lambda (x y) (list (car (apply-reduction-relation/tag-with-names x y))))(term (AS (let ([x (let ([y true]) y)]) x))))

```
(this can be run from "anf.rkt" with "redex/gui" imported in interaction mode or a REPL using this directory. It will take me a while to shrink the example, although it shouldn't be hard https://github.com/wilbowma/multi-lang-comp)

And "reduce" a few times to get this:
<img width="1201" alt="Screen Shot 2021-07-21 at 13 00 11" src="https://user-images.githubusercontent.com/1133598/126552403-525379ef-6b98-4f55-bf2a-c20fb08a6d55.png">

But when I press "fix layout" with the "dot" option, all the arrows disappear:
<img width="431" alt="Screen Shot 2021-07-21 at 13 00 17" src="https://user-images.githubusercontent.com/1133598/126552437-290aeb71-2f29-4ad6-b50e-1d07136f985f.png">

**Comment by rfindler** [comment]
I think that this is always how it has been and, while I agree that it isn't great, the arrows come back if you unclick. The missing piece is parsing and then rendering the arrow information that is coming back from the layout algorithm (ie dot). It comes back as splines, I belive, and I didn't figure out how to turn that into calls to the draw-spline method in `dc<%>`.

**Comment by wilbowma** [comment]
Oh my mistake, thanks!

**Comment by rfindler** [comment]
Okay to close, @wilbowma ?

**Comment by wilbowma** [comment]
Yeah I suppose. Should check that this is documented so I don't run into it again.

**Comment by rfindler** [comment]
I'll update the docs (and then close)
