### ISSUE TITLE
Docs missing a word I can't fill in. 

### ISSUE THREAD

**Issue by jasonhemann** [racket/redex#256]
Documentation currently reads ["The is captured by the keyword shadow."](https://github.com/racket/redex/blob/4c2dc96d90cedeb08ec1850575079b952c5ad396/redex-doc/redex/scribblings/ref/languages.scrbl#L148). It's clear there's something missing, but I don't know what's supposed to go between "The" and "is".

**Comment by rfindler** [comment]
Thanks!
