### ISSUE TITLE
non-deterministic metafunction

### ISSUE THREAD

**Issue by gridaphobe** [racket/redex#31]
I'd like to write a metafunction that non-deterministically generates a term out of thin air. For a while I thought I could make this work with the following:

```
(define-language l
  (v integer)
  (t int))

(define-metafunction l
  gen : t -> v
  [(gen int) ,(generate-term l integer 5)])
```

But I just realized that the unquote is of course being evaluated at compile-time, so `(gen int)` will always return the same integer. It's been a while since I've written scheme.. :)

Is there a way to make use of redex's term generators as part of a metafunction?

**Comment by rfindler** [comment]
You may wish to take comments like these to the racket mailing list https://lists.racket-lang.org/ . You will find more helpful fuller discussions there. I'll give a bare bones answer here, asking you to read the docs for `define-metafunction`, in particular the paragraph beginning "note that":

 http://docs.racket-lang.org/redex/The_Redex_Reference.html?q=define-metafunction#%28form._%28%28lib._redex%2Freduction-semantics..rkt%29._define-metafunction%29%29 

And one last comment: the call to `generate-term` is evaluated only when the metafunction is called, at runtime.
