### ISSUE TITLE
too few args to judgment causes internal error

### ISSUE THREAD

**Issue by andmkent** [racket/redex#32]
The 'assemble' function in redex/private/judgment-form.rkt will throw an internal error 

```
car: contract violation
  expected: pair?
  got: '()
```

if a 'judgment-holds' clause in a metafunction passes too few arguments to the judgment:

```racket
#lang racket/base

(require redex/reduction-semantics)

(define-language L
  [x ::= variable-not-otherwise-mentioned]
  [e :: x (λ x e) (e e)])

(define-judgment-form L
  #:mode (lambda? I)
  #:contract (lambda? e)
  [----------------
   (lambda? (λ x e))])

(define-metafunction L
  not-lambda? : e -> boolean
  [(not-lambda? e)
   #f
   (judgment-holds (lambda?))] ;; <---- causes error
  [(not-lambda? e) #t])
```

http://imgur.com/MTwbZAS

**Comment by rfindler** [comment]
Thanks for the report. (And I wish that "pull request" and "problem report" didn't begin with the same letters.)

**Comment by samth** [comment]
Note that you can leave of the "PR" letters entirely, and github will still figure it out.
