### ISSUE TITLE
`redex-check` sometimes generates variables bound by a metafunction

### ISSUE THREAD

**Issue by florence** [racket/redex#48]
```racket
#lang racket
(require redex rackunit)
(define-language vars
  (x variable-not-otherwise-mentioned))

(define-metafunction vars
  [(U x) x])

;; eventually generates (term U), which is not a valid term
(redex-check vars x (not (equal? (term x) 'U)))
;(term U) ; errors with ``metafunction must be in an application in: U''
```

This happens both with this variant of `redex-check` and with the `#:satisfies` variant.

**Comment by rfindler** [comment]
This is a "valid term" in the sense that if you could write it down, it would be a valid thing to pass to `U`. It isn't valid in the sense that you cannot write `(term U)`, tho, I agree. But I'm not immediately seeing why that is a problem.

**Comment by florence** [comment]
Its an annoyance because when `redex-check` finds a bug I copy that bug into a separate test. But then sometimes that test fails not because of the bug, but because I can't construct the terms in the test.

**Comment by rfindler** [comment]
I agree it is an annoyance. It isn't easy to fix as redex-check doesn't know what metafunctions you have in scope when you type `term`

**Comment by rfindler** [comment]
(you will have in scope, I mean)

**Comment by florence** [comment]
Robby and I agreed that there isn't really a good way to fix this right now.
