### ISSUE TITLE
compile-pattern: unknown cross reference id-id

### ISSUE THREAD

**Issue by wilbowma** [racket/redex#54]
When I try to use `cross` in a language definition, or use `cross` with a non-terminal alias, I get this error.
I'm running redex-lib built from ce1360b79300b08fe1999c32808e3d47cf220c7a.

Here is a test file: https://gist.github.com/wilbowma/4e8dae31a08b7c8eb693d38affa6ee4c

**Comment by rfindler** [comment]
The 'cross' pattern is not intended for direct use like that. What were you intending to achieve?

**Comment by wilbowma** [comment]
The first of those three tests passes, which is why I expected the others to work. My intention was to define a non-terminal representing arbitrary contexts by using `(cross e)`.

**Comment by rfindler** [comment]
Here's the code in question, for easy reference:

```
#lang racket/base

(require
 redex/reduction-semantics)

(define-language lcL
  (e t ::= () (λ (x) e) (e e))
  (C ::= (cross e)))

(module+ test
  (require rackunit)
  (check-true
   (redex-match? lcL (cross e) (term (λ (x) hole))))
  (check-true
   (redex-match? lcL (cross t) (term (λ (x) hole))))
  (check-true
   (redex-match? lcL C (term (λ (x) hole)))))
```

**Comment by rfindler** [comment]
This appears to have been fixed somewhere along the way.
