### ISSUE TITLE
One weird non-terminal that will crash your computer

### ISSUE THREAD

**Issue by wilbowma** [racket/redex#65]
I accidently wrote a language with the following `nf` non-terminal, and tried to use it. I spent a week trying to figure out why running my tests caused Racket to eat all of my computer's memory in a few seconds.

Is there anything to be done to detect/warn the user of this sort of problem?

WARNING: Do not run this code outside of some kind of sandbox.
```racket

#lang racket/base
(require redex/reduction-semantics)

(check-redundancy #t)

(define-language lc-crash
  (e ::= () (λ (x) e) (e e))
  (E ::= hole (E e) (v E))
  (nf ::= x (in-hole E nf))
  ; oops should have been
  #;(nf ::= (in-hole E x)))

(module+ test
  (require rackunit)
  (check-true
   (redex-match? lc-crash nf (term x))))
```

**Comment by rfindler** [comment]
Use DrRacket.

Well, and maybe ask someone to fix the non-terminal cycle checking in redex. (Not sure about that last one yet, need to look more carefully)

**Comment by rfindler** [comment]
Yes, this is definitely a problem with the cycle checking. This program should have produced a syntax error with a message like this:

```
define-language: found a cycle that includes the non-terminal nf
```
