### ISSUE TITLE
Dobule pipes in language not rendered

### ISSUE THREAD

**Issue by leafac** [racket/redex#73]
# Minimal working example

```racket
#lang racket
(require redex)

(define-language pipe
  [operator ::= \| || \|||])

(module+ test
  (test-equal (redex-match? pipe operator (term \|)) #t)
  (test-equal (redex-match? pipe operator (term ||)) #t)
  (test-equal (redex-match? pipe operator (term \|||)) #t))

(render-language pipe)
```

# Expected behavior

The typeset version of the grammar should include the double pipes in `||` and `|||`.

# Current behavior

![untitled_2_-_drracket](https://cloud.githubusercontent.com/assets/586813/16967737/a4257396-4dd8-11e6-9708-5b006c6f80a1.png)

The typeset version of the grammar omits double pipes.

# Caveat

Granted, having pipes on the grammar confuses things, since pipes are already used as `or` in BNF notation. But I'm fine with the font alone distinguishing between BNF operator and language terminal—this lets me stay closer to the language I'm modeling, in which `||` is an operator.

-----

Can you please confirm that my proposal is _indeed_ expected behavior? If so, can you please help me fix it?

Thanks a lot!

**Comment by leafac** [comment]
Opening this Issue revealed a fundamental misunderstanding of Racket's syntax when it comes to pipes (`|`). It turns out that my expectations were wrong—Redex's typesetting was right.

See the corrected snippet, with escapes on every `|` within the identifier:

```racket
#lang racket
(require redex)

(define-language pipe
  [operator ::= \| \|\| \|\|\|])

(module+ test
  (test-equal (redex-match? pipe operator (term \|)) #t)
  (test-equal (redex-match? pipe operator (term \|\|)) #t)
  (test-equal (redex-match? pipe operator (term \|\|\|)) #t))

(render-language pipe)
```

Now the typeset version is what I wanted:

![untitled_3_-_drracket](https://cloud.githubusercontent.com/assets/586813/16968478/1d0c2148-4ddd-11e6-908d-79f724490f39.png)

**Comment by rfindler** [comment]
Glad you got this sorted out!

**Comment by bennn** [comment]
In Racket, `||` is the empty identifier.

Because identifiers are scoped symbols, and any string can be turned to a symbol -- even `"⇒"` or `"λ"` or `"hello world"` -- and we need _something_ to delimit symbols containing whitespace. The delimiter happens to be `|`:

```
> (string->symbol "hello world")
'|hello world|
```

I guess `|` is the delimiter because it's close to the other delimiters on many keyboards and looks kind of like braces.

For the official explanation, search for "|" in the docs: [link](http://docs.racket-lang.org/reference/reader.html?q=%7C#%28part._default-readtable-dispatch%29)

**Comment by leafac** [comment]
@bennn: Thank you for the explanation. I understand what is going on, now.

I didn't know I could search for punctuation on Racket documentation. In all other search engines that I used, it doesn't work, so I just never thought of trying.

Racket keeps impressing me! 👍
