### ISSUE TITLE
run-benchmark shell escaping error

### ISSUE THREAD

**Issue by kach** [racket/redex#77]
Hi! I'm trying to figure out how to run the Redex benchmarks, and I think I have found a bug.

`run-benchmark.rkt` doesn't escape the result of (find-exe) when doing the system call. As a result, standard OSX installs of Racket fail to run `run-benchmark`, because there is a space in the directory name `/Applications/Racket         6.5/bin/racket` and thus `sh` tries to run `/Applications/Racket` rather than the actual binary.

To solve this, I just hardcoded in the binary's path in my installation of Redex. But that's a kludge since I felt bad about editing that file. It would be nice to have this fixed correctly (i.e. correctly escape the directory name when constructing the shell command).

Thanks!

**Comment by samth** [comment]
I think the correct solution is to change these lines: https://github.com/racket/redex/blob/master/redex-benchmark/redex/benchmark/run-benchmark.rkt#L53-L59 to:
```
(apply system* (find-exe) (run-generators) args)
```

**Comment by Hardmath123** [comment]
Yeah, that seems like a better solution. Thanks.
