### ISSUE TITLE
where clauses mess up metafunction error reporting

### ISSUE THREAD

**Issue by andmkent** [racket/redex#8]
Racket Snapshot: 20150728-75e19c9

Having a 'where clause' on a metafunction seems to cause it to be highlighted as the erroneous clause when in fact a later clause is at fault.

Consider the following small redex model:

```racket
#lang racket
(require redex)

(define-language Piano
  (n ::= O (S n)))

(define-metafunction Piano
  sub1 : n -> n
  [(sub1 (S n)) n]
  [(sub1 O) ]) ;; <-- error highlighting here, correct! =D
```
This error correctly reports ' [(sub1 O) ]' is bad since it has no rhs.

However, if we had a where clause to the previous clause:

```racket
#lang racket
(require redex)

(define-language Piano
  (n ::= O (S n)))

(define-metafunction Piano
  sub1 : n -> n
  [(sub1 (S n)) n (where #t #t)]  ;; <-- error highlighting here, wrong =(
  [(sub1 O) ])
```

Now the incorrect clause is highlighted and reported as erroneous in the error message:

![image](https://cloud.githubusercontent.com/assets/3662058/8939313/da38fe48-3520-11e5-8e2c-3e8dbc35d733.png)

**Comment by rfindler** [comment]
Thanks! Fixed: https://github.com/racket/redex/commit/a4d9d465590a5062f651e29460778c9f210b9c2d
