### ISSUE TITLE
Binding form grammer needs documentation

### ISSUE THREAD

**Issue by LeifAndersen** [racket/redex#88]
When you look at the grammar for `#:binding-forms`, you see:

```
maybe-binding-spec =	 	
                                    | #:binding-forms binding-declaration ...
```

Where `binding-decaration` is specified as:

```
binding-declaration = binding-pattern
                                  | binding-pattern #:exports beta
```

The problem is `binding-pattern` itself is undocumented.

If you look at the examples for `#:binding-form`, you can get a sense of what a valid `binding-pattern` is. Namely, it should look something like a term in the language with an additional #:refers-to keyword and what the variable being bound is. But other than that ad-hoc understanding, the documentation is unclear what a valid binding form is. For example, if it needs to be an exact term in the language, then it would make sense to statically check if the term actually appears in the language. If not, what other things could be in a `binding-pattern`.

I would write the documentation for this myself, but I don't have a good grasp on what a `binding-pattern` is either, unless it really is roughly the form of `(term-expr ... #:refers-to var-expr)`.

**Comment by bennn** [comment]
Anecdote: I just realized this is valid

```
(define-language Λ
  [V+ ::= (integer @ l) ((λ (x @ l) E+) @ l)]
  [E+ ::= V+ (x @ l) ((E+ E+) @ l)]
  [l x ::= variable-not-otherwise-mentioned]
  #:binding-forms
    ((λ (x @ l_0) E #:refers-to x) @ l_1))
```

Didn't realize I could use underscores in a  _binding pattern_

**Comment by rfindler** [comment]
A binding-pattern is a pattern with embedded `#:refers-to`s and `#:exports`. (A binding pattern is not a term and not an expr).

**Comment by bennn** [comment]
Ok that's easier than I thought. That should be in the docs (linked to `binding-pattern` in the BNF).

@LeifAndersen are you happy with that explanation / can you think of a way to put that in the grammar?

**Comment by LeifAndersen** [comment]
I think we can have it refer to the `pattern` at the top of the file. Especially as most of the space in that top grammar for `pattern` is spent on terminals.
