### ISSUE TITLE
Should #:binding-forms raise error if form is not in language?

### ISSUE THREAD

**Issue by bennn** [racket/redex#89]
(full example below)

Usually, when I write a `define-language`, I do this:
1. define non-terminals for values, expressions, etc
2. from the non-terminals, pick the _patterns that bind_ and include them in a `#:binding-forms`

If I accidentally write a pattern in my `#:binding-forms` that doesn't match any non-terminal, I've made a mistake.

Should redex check binding patterns against non-terminals in the language and raise an error if the binding pattern doesn't match any non-terminals? If not, how about an optional annotation?

- - -

The example. I'm translating lambda calculus terms (`V`, `E`) into lambda-calculus-terms-annotated-with-labels (`V+` `E+`). This code has a mistake. The second binding pattern doesn't `(redex-match? Λ E+ ....)`.

If you run this code, the call to `alpha-equivalent?` at the bottom returns `#f` fixing the mistake in the `define-language` (changing `E` to `E+`) changes the result to `#t`.

```racket
#lang racket/base
(require redex/reduction-semantics)

(define-language Λ
  [V ::= integer (λ x E)]
  [E ::= V x (E E)]
  [V+ ::= (integer @ l) ((λ (x @ l) E+) @ l)]
  [E+ ::= V+ (x @ l) ((E+ E+) @ l)]
  [N ::= natural]
  [Γ ::= ((x l) ...)]
  [l x ::= variable-not-otherwise-mentioned]
  #:binding-forms
    (λ x E #:refers-to x)
    ((λ (x @ l_0) E #:refers-to x) @ l_1)) ;;; BUG HERE! Should be E+

(define (fresh n)
  (list (string->symbol (format "l~a" n)) (+ n 1)))

(define-judgment-form Λ
  #:mode (annotate I I I O O)
  #:contract (annotate N Γ E E+ N)
  [
   (where (l N_1) ,(fresh (term N)))
   --- Int
   (annotate N Γ integer (integer @ l) N_1)]
  [
   (where (l_1 N_1) ,(fresh (term N_0)))
   (where Γ_1 ,(cons (term (x l_1)) (term Γ_0)))
   (annotate N_1 Γ_1 E E+_2 N_2)
   (where (l_2 N_3) ,(fresh (term N_2)))
   (where E+ ((λ (x @ l_1) E+_2) @ l_2))
   --- Lam
   (annotate N_0 Γ_0 (λ x E) E+ N_3)]
  [
   (where ((x_0 l_0) ... (x l) (x_1 l_1) ...) Γ_0)
   --- Var
   (annotate N_0 Γ_0 x (x @ l) N_0)]
  [
   (annotate N_0 Γ_0 E_0 E+_0 N_1)
   (annotate N_1 Γ_0 E_1 E+_1 N_2)
   (where (l_2 N_3) ,(fresh (term N_2)))
   (where E+_2 ((E+_0 E+_1) @ l_2))
   --- App
   (annotate N_0 Γ_0 (E_0 E_1) E+_2 N_3)])

(let* ([t0 (term ((λ x x) 3))]
       [t1 (car (judgment-holds (annotate 0 () ,t0 E+ N) E+))])
  (alpha-equivalent? Λ
    t1
    (term ((((λ (x @ l0) (x @ l0)) @ l1) (3 @ l2)) @ l3))))
```

**Comment by rfindler** [comment]
I am not sure of the running time of pattern equality (or if it is even decidable). I certainly don't have an algorithm to implement it.

It would be an interesting project to somehow adjust something inside Redex so that we could formulate things like what you're asking for as a predicate to be randomly tested, say. I'm not sure we should try more at the "open issue in Redex" level, tho.

**Comment by bennn** [comment]
the implementation I'm thinking of is:

```
  (redex-match? Λ E? (term ((λ (x @ l_0) E) @ l_1)))
```

So the non-trivial things are:
- erase the `#:refers-to` and `#:exports`
- figure out that `E?` is the right question (but the programmer could give an annotation)

**Comment by rfindler** [comment]
Well, you relying on the fact that `(redex-match Λ E? (term E))` is true, and I don't think that, in general, that pun works. Ditto for `x` and `l_0`.

**Comment by bennn** [comment]
Ok I will close this issue and show what I mean with a pull request at some point in the (distant) future.

**Comment by rfindler** [comment]
Well, I think that it makes sense to expose (perhaps named) versions of the patterns in the #:binding-forms section. But it doesn't work to take a pattern and put `term` around it and then think it is now a term that matches the given pattern. Here is a somewhat natural example where it doesn't work:

```
#lang racket
(require redex)
(define-language L
  ;; deBruijn indicies
  (e ::= (λ e) n (e e))
  (n ::= natural))

(redex-match L (λ (n n)) (term (λ (n n))))
```

Stepping back, the pattern equality (where two patterns are equal iff they match the same terms) is complex. There are a number of theoretical results (that I am not particularly up on) that, I believe, show that, for languages simpler than redex, that problems like these are either worse than exponential or sometimes undecidable. 

I think that TATA is a good place to start if you want to do more here: http://tata.gforge.inria.fr/

**Comment by LeifAndersen** [comment]
So, IIRC, `redex-match?` requires you to have an actual expression, rather than just a grammar rule pattern. Hence why its a bit more tricky.

FWIW, I like either of the suggestions robby has proposed so far.

**Comment by LeifAndersen** [comment]
Also +1 for TATA
