### ISSUE TITLE
`cross` pattern errors when used in a language.

### ISSUE THREAD

**Issue by florence** [racket/redex#92]
The program 

```
#lang racket
(require redex/reduction-semantics)
(define-language one
  (p ::= nothing)
  (C ::= (cross p)))
```

Errors with `compile-pattern: unknown cross reference p-p`. 

The program:

```
#lang racket
(require redex/reduction-semantics)
(define-language one
  (p ::= nothing))
(define-metafunction one
  test : (cross p) -> any
  [(test (cross p)) 1])
```

Runs without error.

**Comment by rfindler** [comment]
I think that this is probably a missing check. I never sorted out when `cross` should be allowed in "user" code (it is intended to be used internally in the context closure of a reduction relation).

**Comment by mfelleisen** [comment]
@rfindler 

I have never used this cross feature before. The documentation confuses me a lot: 

"	• The (cross id) pattern is used for the compatible closure functions. If the language contains a non-terminal with the same name as id, the pattern (cross id) matches the context that corresponds to the compatible closure of that non-terminal.”

QUESTIONS: 

Does this mean there is more than one compatible closure function? Which one does it pick? 

What does it mean to correspond to a compatible closure (of a non-terminal)? 

Does it mean (cross id) matches a context? So if I were to define 

 e ::= number | (+ e e) | (cross e)

I’d automatically include C which is defined as [] | (+ C e) | (+ e C) ?

**Comment by wilbowma** [comment]
See also: #54

**Comment by leafac** [comment]
I found this issue after getting confused trying to read the [little documentation available on `cross`](https://docs.racket-lang.org/redex/The_Redex_Reference.html#%28tech._cros%29). I suggest we either remove `cross` from the documentation or provide better explanations and examples.

**Comment by rfindler** [comment]
I think that we should remove `cross` from the surface language of Redex (letting it be used only from the internal things). Its existence predates the ability for redex to distinguish internal from external things in patterns.

**Comment by leafac** [comment]
Let me know if there’s some way I can help with that.

**Comment by rfindler** [comment]
@mfelleisen I somehow missed your earlier comments. As for "which function does it pick", there is a client/server confusion somewhere. Here is what is happening. There are functions in Redex. Those functions sometimes need to know what the compatible closure is for various reasons. They access it via the pattern `cross`. If you were to define this language:

```
(define-language L (e ::= (+ e e) number))
```

then the pattern `(cross e)` in that language would match the same thing as the pattern `C` in this language:

```
(define-language L 
  (e ::= (+ e e) number)
  (C ::= (+ e C) (+ C e) hole))
```

(The general case is more complex, of course.)

**Comment by rfindler** [comment]
PS: if you write `cross` in a language yourself then it isn't clear what `cross`ing a `cross` would do.... Best to think of that pattern as not being allowed to appear in a `define-language` at all. Then a transformation happens that sticks new "hidden" non-terminals (like the `C` derived from `e` above) and `cross` gives you access to those non-terminals.

**Comment by rfindler** [comment]
@leafac if you want to remove `cross` from the pattern language that would be great. This may turn out to be a backwards incompatible change that actually matters. It is definitely backwards incompatible but we might be able to get away with it. I guess a first step is to check with @dvanhorn : do you use `cross` in any of your models, David?

As for how to implement it, probably what I would do is to remove `cross` from [this function](https://github.com/racket/redex/blob/master/redex-lib/redex/private/rewrite-side-conditions.rkt#L50) and then see what breaks. Ideally it would turn just into the datum `cross`, but it might make sense to make it a syntax error temporarily to quantify the breakage.

I guess there would need to be some kind of "backdoor" access to `cross` in order to implement the compatible closure function. Maybe it is already set up using a lower-level API, tho. I can't recall. I'm also not sure what else would be needed. Maybe nothing. Either way, more test cases are needed. :)

**Comment by leafac** [comment]
I started working on removing `cross` from Redex. Yesterday I [followed the tutorial on the blog](http://blog.racket-lang.org/2017/09/tutorial-contributing-to-racket.html) and setup my machine for working on Redex. My previous contributions were mostly on documentation, so I had never bothered to go through the setup. Today, I contributed with other things (https://github.com/racket/redex/pull/144, https://github.com/racket/redex/pull/145 and https://github.com/racket/redex/pull/146), so I didn’t have the time to work on `cross`. Tomorrow I’ll try to remove `cross` from the documentation, which is a low-hanging fruit and will get the ball rolling. I intend to open a **work-in-progress** pull request by then, so you can help me work on this issue publicly through GitHub.

**Comment by rfindler** [comment]
Looks like this got fixed to make `cross` actually work somewhere along the way.
