### ISSUE TITLE
Underscores in binding-pattern causes match failure

### ISSUE THREAD

**Issue by cobbal** [racket/redex#93]
It appears that leaving an underscore in a binding-pattern can cause pattern matching to mysteriously fail at a later point.

```racket
#lang racket
(require redex/reduction-semantics)

(define-language L
 (v ::=
  (clo σ v)
  number)
 (σ ::= [x v])
 (x ::= variable-not-otherwise-mentioned)
 #:binding-forms
 (clo [x _] v #:refers-to (shadow x)))
;;       ⬑ problem here

(module+ test
 (require rackunit)

 (define example-v (term (clo [x 3] 2)))

 (check-true (redex-match? L v example-v)) #;passes
 (check-true (redex-match? L (clo [x v_0] v_1) example-v)) #;fails)
```

If the underscore is changed to a `v_0`, all tests pass. I'm not sure what the underscore is being parsed as (not documented see #88), but I expected it to be a "don't care" as in normal patterns.

**Comment by cobbal** [comment]
Forgot to mention, this is on Racket v6.8; I haven't tested on any other versions.

**Comment by rfindler** [comment]
Here's a slightly simpler version, where nearly any change I make (including replacing some `v`s with `any`s) makes the bug go away.

```
#lang racket
(require redex/reduction-semantics)

(define-language L1
  (v ::= (clo [x any_1] any) number)
  (x ::= variable-not-otherwise-mentioned)
  #:binding-forms
  (clo [x _] v #:refers-to x))
;;        ⬑ problem here

(define-language L2
  (v ::= (clo [x any_1] any) number)
  (x ::= variable-not-otherwise-mentioned)
  #:binding-forms
  (clo [x any] v #:refers-to x))

(define example-v (term (clo [x 3] 2)))

(redex-match? L1 (clo [x v_0] any_1) example-v) #;passes
(redex-match? L2 (clo [x v_0] any_1) example-v) #;fails
```

**Comment by rfindler** [comment]
What seems to be happening is that the freshening function has a loop that traverses the pattern following the `#:binding-forms`:

https://github.com/racket/redex/blob/master/redex-lib/redex/private/binding-forms.rkt#L639

that doesn't also traverse the term that was matched. Instead it has only the result of the pattern matching that Redex did (or, in other words, bindings for the redex variables). So when it encounters the `_`, there is no binding for it (which is correct), but the freshener has discarded the original term at that point so it cannot plug back in whatever was there before.

**Comment by rfindler** [comment]
There are definitely issues with the code I just pushed, but I closed the issue anyway, since the symptom is fixed. Feel free to re-open or create a new one if you run across a more complex example that breaks.

Thanks for the feedback!
