### ISSUE TITLE
Add prolog "cut" option to `define-metafunction`

### ISSUE THREAD

**Issue by bennn** [racket/redex#95]
It would be useful if `define-metafunction` could commit to a branch after matching an "argument pattern". This way, argument patterns lower in the function can assume they will not be matched against values that would match earlier patterns (just like `cond`) ---- even if `side-condition`s or `where` clauses within the above metafunction branches failed.

Here's a small example,
the first branch of the `apply` metafunction checks if the first argument is a lambda.
The second branch assumes its argument is not a lambda, but the first branch has a bug that makes this assumption false.

```
#lang racket/base

(require redex/reduction-semantics)

(define-language LC
  [e ::= v (e e)]
  [v ::= x (λ x e)]
  [x ::= variable-not-otherwise-mentioned]
  #:binding-forms (λ x e #:refers-to x))

(define-metafunction LC
  apply : e v -> e
  [(apply (λ x e) v)
   (substitute e x v)
   (where #true #false)]
  [(apply e v)
   ,(error 'apply "cannot apply non-function ~a" (term e))])

(term (apply (λ x (λ y x)) z))
;; Confusing error message: cannot apply non-function (λ x .....)
```

Thanks to @julbinb for pointing this out.

**Comment by bennn** [comment]
I'm thinking the way to implement this is with an optional argument to `define-metafunction`, e.g.

```
(define-metafunction LC
  #:commit
  apply : e v -> e
  [.... ....])
```

**Comment by bennn** [comment]
On second thought, maybe it's better to just clarify the documentation for `define-metafunction` and point to `where/error`.

(Personally, I would probably avoid `define-metafunction ... #:commit` because I like simple argument patterns with fine-grained matching in the `where` clauses)

**Comment by rfindler** [comment]
I agree that `where/error` is probably better here. Do you have a more concrete docs suggestion in mind?

**Comment by bennn** [comment]
No, but I can think about it & submit ideas as a PR if you want to close this

**Comment by rfindler** [comment]
I think that adding something like "cut" would go against the main design principle of redex, since people's papers generally don't contain metafunctions with that kind of behavior. So, yeah, I'll close this. Thanks, Ben.
